
import Memory.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Behic
 */
public class MemoryApp extends javax.swing.JFrame {

    /**
     * Creates new form MemoryApp
     */
    public MemoryApp() {
        initComponents();
        taDisplayDeficit.setEditable(false);
        taSearch.setEditable(false);
        taTotalDeficit.setEditable(false);
        pnlAmnesia.setVisible(false);
        pnlAlzheimer.setVisible(false);
        cbAffectedArea.setSelectedIndex(-1);
        cbBrainL.setSelectedIndex(-1);
        cbCause.setSelectedIndex(-1);
        cbMemoryLoss.setSelectedIndex(-1);
        cbSearch.setSelectedIndex(-1);
        cbType.setSelectedIndex(-1);
        cbSearch.removeAllItems();
        this.setResizable(false);
        this.setAlwaysOnTop(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDeficitID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbMemoryLoss = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPatientID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPatientSurname = new javax.swing.JTextField();
        tfPatientName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbAmnesia = new javax.swing.JRadioButton();
        rbAlzheimer = new javax.swing.JRadioButton();
        pnlAmnesia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        cbCause = new javax.swing.JComboBox<>();
        cbBrainL = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jbDisplayDeficit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplayDeficit = new javax.swing.JTextArea();
        jbTotalDeficits = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTotalDeficit = new javax.swing.JTextArea();
        jbSearch = new javax.swing.JButton();
        cbSearch = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taSearch = new javax.swing.JTextArea();
        pnlAlzheimer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbAffectedArea = new javax.swing.JComboBox<>();
        jbAddDeficit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memory Deficts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Deficit ID:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Memory Loss:");
        jLabel2.setToolTipText("");

        cbMemoryLoss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbMemoryLoss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Implicit", "Dementia", "Interference", "Repression", "Anterograde" }));
        cbMemoryLoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemoryLossActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Clinical Cases");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Patient ID:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Patient Name, Surname:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Age:");
        jLabel6.setToolTipText("");

        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Gender");
        jLabel7.setToolTipText("");

        tfGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenderActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Deficit Type");
        jLabel8.setToolTipText("");

        rbAmnesia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbAmnesia.setText("Amnesia");
        rbAmnesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmnesiaActionPerformed(evt);
            }
        });

        rbAlzheimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbAlzheimer.setText("Alzheimer");
        rbAlzheimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlzheimerActionPerformed(evt);
            }
        });

        pnlAmnesia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Amnesia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Type:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cause:");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Brain Location:");
        jLabel11.setToolTipText("");

        cbType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retrograde", "Anterograde", "Dissociative", "Drug-induced", "Post-traumatic" }));

        cbCause.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbCause.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brain Infection", "Dementia", "Anoxia", "Damage to the hippocampus", "Head injuries", "Alcohol use", "Trauma or stress", "Electroconvulsive therapy (ECT)" }));
        cbCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCauseActionPerformed(evt);
            }
        });

        cbBrainL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbBrainL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hipocampus", "Hypothalamus", "Thalamus", "Cerebral Cortex", "Brainstem" }));

        javax.swing.GroupLayout pnlAmnesiaLayout = new javax.swing.GroupLayout(pnlAmnesia);
        pnlAmnesia.setLayout(pnlAmnesiaLayout);
        pnlAmnesiaLayout.setHorizontalGroup(
            pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmnesiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAmnesiaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAmnesiaLayout.createSequentialGroup()
                        .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBrainL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbCause, 0, 0, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlAmnesiaLayout.setVerticalGroup(
            pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmnesiaLayout.createSequentialGroup()
                .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(cbCause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlAmnesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbBrainL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAmnesia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfPatientSurname))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfDeficitID, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(cbMemoryLoss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(tfPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbAmnesia)
                                .addGap(18, 18, 18)
                                .addComponent(rbAlzheimer)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDeficitID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbMemoryLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPatientSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbAmnesia)
                    .addComponent(rbAlzheimer))
                .addGap(18, 18, 18)
                .addComponent(pnlAmnesia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display and Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jbDisplayDeficit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbDisplayDeficit.setText("Display Deficit");
        jbDisplayDeficit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDisplayDeficitActionPerformed(evt);
            }
        });

        taDisplayDeficit.setColumns(20);
        taDisplayDeficit.setRows(5);
        jScrollPane1.setViewportView(taDisplayDeficit);

        jbTotalDeficits.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbTotalDeficits.setText("Total Deficits");
        jbTotalDeficits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTotalDeficitsActionPerformed(evt);
            }
        });

        taTotalDeficit.setColumns(20);
        taTotalDeficit.setRows(5);
        jScrollPane2.setViewportView(taTotalDeficit);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbDisplayDeficit)
                            .addComponent(jbTotalDeficits, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbDisplayDeficit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTotalDeficits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSearch.setText("Search by Deficit ID:");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        cbSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        taSearch.setColumns(20);
        taSearch.setRows(5);
        jScrollPane3.setViewportView(taSearch);

        pnlAlzheimer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alzheimer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Affected Area: ");
        jLabel12.setToolTipText("");

        cbAffectedArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbAffectedArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cognition", "Cerebral Cortex", "Entorhinal Cortex", "Hippocampus" }));

        javax.swing.GroupLayout pnlAlzheimerLayout = new javax.swing.GroupLayout(pnlAlzheimer);
        pnlAlzheimer.setLayout(pnlAlzheimerLayout);
        pnlAlzheimerLayout.setHorizontalGroup(
            pnlAlzheimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlzheimerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbAffectedArea, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        pnlAlzheimerLayout.setVerticalGroup(
            pnlAlzheimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlzheimerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlAlzheimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbAffectedArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbAddDeficit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAddDeficit.setText("Add Deficit");
        jbAddDeficit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddDeficitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAlzheimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jbAddDeficit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlAlzheimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAddDeficit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSearch)
                            .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbMemoryLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemoryLossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMemoryLossActionPerformed

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void tfGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenderActionPerformed

    private void cbCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCauseActionPerformed

    private void jbAddDeficitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddDeficitActionPerformed
        
        if(rbAmnesia.isSelected()==true){
         Amnesia a = new Amnesia(cbType.getSelectedItem().toString(),cbCause.getSelectedItem().toString(),cbBrainL.getSelectedItem().toString(),tfDeficitID.getText(),cbMemoryLoss.getSelectedItem().toString(),tfPatientID.getText(),tfPatientName.getText(),tfPatientSurname.getText(),Integer.parseInt(tfAge.getText()),tfGender.getText());
          taDisplayDeficit.setText(taDisplayDeficit.getText()+ "Amnesia is added.\n");
          InfoClass.addMemory(a);
          cbSearch.addItem(tfDeficitID.getText());
       }   
      else if (rbAlzheimer.isSelected()== true){
          Alzheimer al = new Alzheimer(cbAffectedArea.getSelectedItem().toString(),tfDeficitID.getText(),cbMemoryLoss.getSelectedItem().toString(),tfPatientID.getText(),tfPatientName.getText(),tfPatientSurname.getText(),Integer.parseInt(tfAge.getText()),tfGender.getText());
          taDisplayDeficit.setText(taDisplayDeficit.getText()+ "Alzheimer is added.\n");
          cbSearch.addItem(tfDeficitID.getText());
          InfoClass.addMemory(al);
      }  
        tfAge.setText("");
        tfDeficitID.setText("");
        tfGender.setText("");
        tfPatientID.setText("");
        tfPatientName.setText("");
        tfPatientSurname.setText("");
        pnlAlzheimer.setVisible(false); 
        pnlAmnesia.setVisible(false);
        rbAmnesia.setSelected(false);
        rbAlzheimer.setSelected(false);
        cbMemoryLoss.setSelectedIndex(-1);
    }//GEN-LAST:event_jbAddDeficitActionPerformed

    private void rbAmnesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmnesiaActionPerformed
        pnlAmnesia.setVisible(true);
        pnlAlzheimer.setVisible(false);   
        rbAlzheimer.setSelected(false);
        
    }//GEN-LAST:event_rbAmnesiaActionPerformed

    private void rbAlzheimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlzheimerActionPerformed
        pnlAlzheimer.setVisible(true);
        pnlAmnesia.setVisible(false);
        rbAmnesia.setSelected(false);
    }//GEN-LAST:event_rbAlzheimerActionPerformed

    private void jbDisplayDeficitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDisplayDeficitActionPerformed
        if(rbAmnesia.isSelected()==true){
            taDisplayDeficit.setText(InfoClass.getAmnesia());
        }
        else if(rbAlzheimer.isSelected()==true){
            taDisplayDeficit.setText(InfoClass.getAlzheimer());
        }
        else{
            taDisplayDeficit.setText(InfoClass.getAllMemory());
        }
        
    }//GEN-LAST:event_jbDisplayDeficitActionPerformed

    private void jbTotalDeficitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTotalDeficitsActionPerformed
       taTotalDeficit.setText(InfoClass.showTotalMemory());
    }//GEN-LAST:event_jbTotalDeficitsActionPerformed

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        taSearch.setText(InfoClass.searchMemory(cbSearch.getSelectedItem().toString()).toString());
                
    }//GEN-LAST:event_jbSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryApp().setVisible(true);
                
                        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAffectedArea;
    private javax.swing.JComboBox<String> cbBrainL;
    private javax.swing.JComboBox<String> cbCause;
    private javax.swing.JComboBox<String> cbMemoryLoss;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAddDeficit;
    private javax.swing.JButton jbDisplayDeficit;
    private javax.swing.JButton jbSearch;
    private javax.swing.JButton jbTotalDeficits;
    private javax.swing.JPanel pnlAlzheimer;
    private javax.swing.JPanel pnlAmnesia;
    private javax.swing.JRadioButton rbAlzheimer;
    private javax.swing.JRadioButton rbAmnesia;
    private javax.swing.JTextArea taDisplayDeficit;
    private javax.swing.JTextArea taSearch;
    private javax.swing.JTextArea taTotalDeficit;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfDeficitID;
    private javax.swing.JTextField tfGender;
    private javax.swing.JTextField tfPatientID;
    private javax.swing.JTextField tfPatientName;
    private javax.swing.JTextField tfPatientSurname;
    // End of variables declaration//GEN-END:variables
}
